### ISSUE TITLE
Suggestion: Implement Reverse Geocoding

### ISSUE THREAD

**Issue by nyghtly-derek** [doersino/earthacrosstime#3]
That would provide some compelling context to go along with the imagery. For example, country or city name.

Did a quick search to see how easy it is to do in Python. This looks promising: https://towardsdatascience.com/reverse-geocoding-in-python-a915acf29eb6

**Comment by doersino** [comment]
Ever watched one of the generated videos 'til the end? 😉

**Comment by doersino** [comment]
Closing this issue for now since it’s already implemented using a similar approach to what’s described in the blog post you’ve linked.
